### PR TITLE
Pull Request for #9: Prepare release for Dataverse

### PR DESCRIPTION
**Pull request by santiagohermo**
Can you review this pull for #9 @jmshapir @miikapaal? I added code to produce a `release.zip` that will be uploaded to Harvard's Dataverse. A first version of the zip file is in [this Google Drive folder](https://drive.google.com/drive/u/1/folders/1gfskfTa4UAgogjf_i6Z5kvR0Vuk-bY5x).

#### Files added

- `codebook.Rmd`: uses as input the `README` and other data in the repo and ~created~ _creates_ a `codebook.md` that will be attached to the Harvard Dataverse release.

- `release.py` compiles `codebook.Rmd` and creates the `release.zip` including only the raw pdf of the Läroplaner and the final csv output.

#### Review

I think we should:

- Check that we include everything we want in the zip file.
- Review `codebook.md` and add other information that may be relevant
  - It would be really easy to save this file as `pdf` instead of `md`, which I think would be more convenient in this case. Should we switch?
- Review the code and make sure it works on Mac as well.

Feel free to take a look as well if you have time @dagese!

#### Next steps

Per [the opening comment](https://github.com/JMSLab/LaroplanOCR/issues/9#issue-1176766313):

- Post a release in github
- Upload to the Dataverse
- Take the repository public

### CODE REVIEW

**Review by jmshapir — CHANGES_REQUESTED** [review]
Nice work @santiagohermo!

I've included a few comments/questions.

**Review by santiagohermo — COMMENTED** [review]
Thanks @jmshapir! I replied to your comments and implemented several changes in https://github.com/JMSLab/LaroplanOCR/pull/10/commits. I also added the LICENSE to the zip file.

I updated the [shared folder](https://drive.google.com/drive/u/1/folders/1gfskfTa4UAgogjf_i6Z5kvR0Vuk-bY5x). Because I removed the pdf files of the curricula, the file now only weights 3mb. We could store it in the repo if desired.

**Review by miikapaal — APPROVED** [review]
Thanks @santiagohermo @jmshapir! The `release.zip` folder looks good to me. I only had minor comments, so I'll approve.

Some replies to https://github.com/JMSLab/LaroplanOCR/pull/10#issue-1195294131 below:
* I only had one suggestion for additions to the compiled `codebook.md` file, related to providing information on where we downloaded the original PDF files.
* I compiled the folder on my Mac using `release.py` without problems. (I did not run the other steps in the repo since we've had another person run the scripts already.) I reviewed the code and have no comments.
* Providing a PDF version of CODEBOOK.MD would be a bit better since some users may not use an editor that allows previewing MD files. If the PDF looks anything like [this](https://github.com/JMSLab/LaroplanOCR/files/8441786/codebook.pdf) (I compiled it manually from VSCode using [`prince`](https://www.princexml.com)), then it would be great!

**Review by jmshapir — COMMENTED** [review]
@santiagohermo @miikapaal I went through and replied on some open threads.

I also took a quick look at the new release.zip and all looks good.

Once we converge on a few of these minor points I'll plan to take a last look and hopefully approve so we can upload.

Thanks!

**Review by jmshapir — APPROVED** [review]
Thanks @santiagohermo!

This version looks good from my side.

**Comment by jmshapir** [comment]
@santiagohermo @miikapaal 

image

**Comment by jmshapir** [comment]
@santiagohermo is there a way you can give me access to edit the Dataverse metadata?

**Comment by jmshapir** [comment]
@santiagohermo is there a way you can give me access to edit the Dataverse metadata?

**Comment by santiagohermo** [comment]
> @santiagohermo is there a way you can give me access to edit the Dataverse metadata?

I think so @jmshapir. What user do you prefer? I guess you should receive an email once I "save changes"

image

**Comment by jmshapir** [comment]
@santiagohermo let's try "@jmshapir" and see what happens. :-)

**Comment by santiagohermo** [comment]
> @santiagohermo let's try "@jmshapir" and see what happens. :-)

Done @jmshapir! Let me know what happens on your side.

image

**Comment by jmshapir** [comment]
Thanks @santiagohermo!

I did the following:
* Edited the "Notes" field to point back to the github repo.
* Edited the "Terms" to use the same terms as the [LICENSE](https://github.com/JMSLab/LaroplanOCR/blob/712ebec830670d37c00438de0df0afba9297e480/LICENSE) that we have in the repo.

If these changes look good to you @santiagohermo, can you "Publish" them in the Dataverse?

image

**Comment by santiagohermo** [comment]
Thanks @jmshapir! [Your changes](https://github.com/JMSLab/LaroplanOCR/pull/10#issuecomment-1093326820) look good, so I published them. It asked me to change the version :/, so I went up to 1.1.

I think we are ready to wrap up this issue?

**Comment by jmshapir** [comment]
@santiagohermo thanks!

Agreed, I have nothing else in mind to do here, so we're good to wrap up from my side, too.

**Comment by santiagohermo** [comment]
Small issue @jmshapir. Because we completed the release before merging this PR, the release points to the incorrect commit

image

If you agree we can delete the release and recreate it with the same tag. We would need to follow the steps [here](https://stackoverflow.com/a/8044605/15344214).

**Comment by santiagohermo** [comment]
Summary [here](https://github.com/JMSLab/LaroplanOCR/issues/9#issuecomment-1094041653)

**Comment by jmshapir** [comment]
> If you agree we can delete the release and recreate it with the same tag. We would need to follow the steps [here](https://stackoverflow.com/a/8044605/15344214).

@santiagohermo sounds fine to me, thanks!

**Comment by santiagohermo** [comment]
Thanks @jmshapir! The problem was fixed and now [the release](https://github.com/JMSLab/LaroplanOCR/releases/tag/v1.0.0) points to the correct commit.

**Pull request merged**
